spring.application.name=petweb

# Configurações do banco
spring.datasource.url=jdbc:postgresssql://localhost:5432/petweb_db
spring.datasource.username=postgres
spring.datasource.password=postdba

 
#Atualizar o BD automaticamente
spring.jpa.hibernate.ddl-auto=update
 
#Exibir no Terminal o SQL sendo executado
spring.jpa.show-sql=true

#Limpar o cache para a execução do Thymeleaf
spring.thymeleaf.cache = false

#Configurações de servidor
server.port=8080
 
#Informa para não formatar o SQL
spring.jpa.properties.hibernate.format_sql=false
